# Generated by Django 5.1.1 on 2025-04-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='TopBanner',
        ),
        migrations.CreateModel(
            name='BannerProduc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_product', models.ImageField(upload_to='banner_product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_product', to='shop.product')),
            ],
        ),
    ]
