# Generated by Django 5.1.1 on 2025-04-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_banner_topbanner_bannerproduc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='publish',
        ),
    ]
