# Generated by Django 5.1.1 on 2025-04-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_status_product_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='categories_picture/'),
        ),
    ]
