# Generated by Django 5.1.1 on 2025-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerproduc',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bannerproduc',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
