# Generated by Django 5.1.1 on 2025-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_verifycode_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
