# Generated by Django 5.1.1 on 2025-04-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_verifycode_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
