# Generated by Django 5.1.1 on 2025-04-30 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_userprofile_user_remove_wishlist_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
