# Generated by Django 5.1.1 on 2025-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_usermore'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermore',
            name='addres',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
