# Generated by Django 5.1.1 on 2025-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_usermore_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermore',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
