# Generated by Django 5.1.1 on 2025-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='addres',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
