# Generated by Django 5.1.1 on 2025-05-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_authority_addres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='order',
        ),
        migrations.AddField(
            model_name='authority',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
