# Generated by Django 5.1.1 on 2025-05-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_authority_order_authority_tracking_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
