# Generated by Django 5.1.1 on 2025-05-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='blog/')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=60)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.blogtag')),
            ],
        ),
    ]
