# Generated by Django 5.1.1 on 2025-05-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_blogtag_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
