# Generated by Django 5.1.1 on 2025-05-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_blog_tag_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
    ]
