# Generated by Django 5.1.1 on 2025-05-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_blog_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
