# Generated by Django 5.1.1 on 2025-05-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish',
        ),
    ]
